services:
  backend:
    container_name: camagru
    # image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace/camagru:cached
    ports:
      - 3000:3000

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 8080:80
    depends_on:
      - backend
